### ISSUE TITLE
uuhh... 

### ISSUE THREAD

**Issue by 3DGameMaker** [PenguinAI-Ext/extension#1]
is it supposed to give me TypeError: Cannot read properties of undefined (reading 'split')  or is there a bug..  it also says Failure to swap extensions will cause the extension to be flatout removed, are you sure the inputed extension has matching id's and has no errors?  ... idk im not very good at js

**Comment by cicerorph** [comment]
No it's not, but that is a problem with the server, i recommend you change the Reverse Proxy Base URL to: https://penguinai.milosantos.com/v1

As it's the newer version of our server made by [Abby](https://github.com/milodev123)
