### ISSUE TITLE
Add Audio capabilities

### ISSUE THREAD

**Issue by OpenMachinesAI** [PenguinAI-Ext/extension#2]
I wanna make a voice interface in penguinmod. Please add other modalities like GPT-4o's voice and audio input/output and gemini's audio input

**Comment by cicerorph** [comment]
There are no way of doing it using OpenAI's API, if you're talking about Text2Speech or Speech2Text, use the extensions that were already made for it.

**Comment by cicerorph** [comment]
Closing this as it's not a actual issue.

**Comment by OpenMachinesAI** [comment]
I’m referring to the real-time api not whisper

**Comment by cicerorph** [comment]
> I’m referring to the real-time api not whisper

If it's not a problem, could you send the docs url for it?

**Comment by OpenMachinesAI** [comment]
https://platform.openai.com/docs/guides/audio

or if you wanna go down the webhook route: https://platform.openai.com/docs/guides/realtime

**Comment by cicerorph** [comment]
> https://platform.openai.com/docs/guides/audio
> 
> or if you wanna go down the webhook route: https://platform.openai.com/docs/guides/realtime

Due to current pricing, we may not implement this feature. However, if OpenAI offers more competitive rates in the future, we might reconsider adding it.
