### ISSUE TITLE
What are the sources for the AI?

### ISSUE THREAD

**Issue by ccocks** [PenguinAI-Ext/extension#4]
I discovered the endpoint https://penguinai.milosantos.com/ but I'm not able to see where the responses are coming from behind the scenes. Seeing the source code for that would be very helpful

**Comment by cicerorph** [comment]
We can't share our source code for security reasons, and we are also not giving out where our responses are coming from behind the scenes as it would just do great damage to other Projects that stands for "Free AI", as of such I'm closing this Issue.

**Comment by ccocks** [comment]
@cicerorph  I think you misunderstood my question. I was wondering about the privacy of the prompts. And also whos paying for it? Gpt models are not open-sources, so they have to be running on OpenAI, which is paid. Also, is using the API for my own projects allowed? (Low usage only)

**Comment by cicerorph** [comment]
> @cicerorph I think you misunderstood my question. I was wondering about the privacy of the prompts. And also whos paying for it? Gpt models are not open-sources, so they have to be running on OpenAI, which is paid. Also, is using the API for my own projects allowed? (Low usage only)

No one will ever see your prompts, they are fully anonymous, you can use the API for your own projects, only if it's not receiving any type of money from it other than donations (which the money **can** be given to PenguinAI aswell)

**Comment by ccocks** [comment]
Thanks for the info, my site has a free amount of credits, but when it is over, they have to pay. I don't know if that counts. Also, Are there "vision" models? Not Image-Generation but Image-Analyzation, like GPT-4o has?

**Comment by cicerorph** [comment]
> Thanks for the info, my site has a free amount of credits, but when it is over, they have to pay. I don't know if that counts. Also, Are there "vision" models? Not Image-Generation but Image-Analyzation, like GPT-4o has?

Yes there are, you can manually check the models using the endpoint we have "/v1/models"
