### ISSUE TITLE
Errors in script something to do with Sandboxing

### ISSUE THREAD

**Issue by solhost** [PenguinAI-Ext/extension#7]
So everytime I try to upload the extension (using the .js file) I get this error: **Error in sandboxed script: blob:https://studio.penguinmod.com/9cda43d4-f2fe-401e-87c3-60b17b4d5942** Have no idea what this is, can someone help me with this issue, thanks 
![Screenshot 2024-11-24 150427](https://github.com/user-attachments/assets/1c95685c-59df-4b62-bd8a-fd0bee35bd03)
(I am using the DuckDuckGo Browser)

**Comment by solhost** [comment]
I have tried many browsers none work

**Comment by cicerorph** [comment]
Could you possibly check the browser's console when you load it?

You can do that by clicking the F12 button.

**Comment by solhost** [comment]
Alright, thanks I will try that
