### ISSUE TITLE
Please see MubiLob

### ISSUE THREAD

**Issue by solhost** [PenguinAI-Ext/extension#8]
I cant even launch the extension, it throws this error (USING THE .js FILE)
![Screenshot 2024-11-24 150427](https://github.com/user-attachments/assets/1d3fe9d8-ff9d-4380-84e7-21bd354b1d60)

(I have not added the thumbnail or anything other then the code just to test if it was legit)
(I have tried not using sandbox)
(I am using the DuckDuckGo Browser)
So, can anybody help me with this error, Thanks

**Comment by solhost** [comment]
I have tried many browsers none work

**Comment by cicerorph** [comment]
Please don't create multiple issues for one reason.
